{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d7e3068-12b9-48e0-a163-565586e66b94",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "import time\n",
    "import sqlite3\n",
    "from datetime import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# OpenWeatherMap API Configuration\n",
    "API_KEY = \"2e8a8c238b72f0695521a0507766af38\"\n",
    "BASE_URL = \"http://api.openweathermap.org/data/2.5/weather\"\n",
    "CITY_IDS = {\n",
    "    \"Delhi\": 1273294,\n",
    "    \"Mumbai\": 1275339,\n",
    "    \"Bangalore\": 1277333,\n",
    "    \"Kolkata\": 1275004,\n",
    "    \"Hyderabad\": 1269843\n",
    "}\n",
    "\n",
    "# Database Configuration\n",
    "DB_NAME = \"weather_data.db\"\n",
    "\n",
    "# Alerting Thresholds\n",
    "TEMP_THRESHOLD = 15  # Celsius\n",
    "\n",
    "def get_weather_data(city_id):\n",
    "    \"\"\"Retrieve weather data from OpenWeatherMap API\"\"\"\n",
    "    params = {\n",
    "        \"id\": city_id,\n",
    "        \"appid\": API_KEY,\n",
    "        \"units\": \"metric\"  # Use metric units for temperature\n",
    "    }\n",
    "    response = requests.get(BASE_URL, params=params)\n",
    "    data = response.json()\n",
    "\n",
    "    # Check if the response contains the expected data\n",
    "    if response.status_code != 200 or 'main' not in data:\n",
    "        print(f\"Error retrieving data for city ID {city_id}: {data.get('message', 'Unknown error')}\")\n",
    "        return None\n",
    "    return data\n",
    "\n",
    "def convert_temperature(temp_in_kelvin):\n",
    "    \"\"\"Convert temperature from Kelvin to Celsius\"\"\"\n",
    "    return temp_in_kelvin - 273.15\n",
    "\n",
    "def calculate_daily_summary(weather_data):\n",
    "    \"\"\"Calculate daily summary from weather data\"\"\"\n",
    "    daily_summary = {\n",
    "        \"date\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
    "        \"avg_temp\": 0,\n",
    "        \"max_temp\": float(\"-inf\"),\n",
    "        \"min_temp\": float(\"inf\"),\n",
    "        \"dominant_weather\": \"\"\n",
    "    }\n",
    "\n",
    "    for data in weather_data:\n",
    "        daily_summary[\"avg_temp\"] += data[\"temp\"]\n",
    "        daily_summary[\"max_temp\"] = max(daily_summary[\"max_temp\"], data[\"temp\"])\n",
    "        daily_summary[\"min_temp\"] = min(daily_summary[\"min_temp\"], data[\"temp\"])\n",
    "        # Determine dominant weather condition\n",
    "        if daily_summary[\"dominant_weather\"] == \"\":\n",
    "            daily_summary[\"dominant_weather\"] = data[\"weather\"]\n",
    "        elif data[\"weather\"] != daily_summary[\"dominant_weather\"]:\n",
    "            daily_summary[\"dominant_weather\"] = \"Mixed\"\n",
    "\n",
    "    daily_summary[\"avg_temp\"] /= len(weather_data) if weather_data else 1\n",
    "    return daily_summary\n",
    "\n",
    "def store_daily_summary(daily_summary):\n",
    "    \"\"\"Store daily summary in SQLite database\"\"\"\n",
    "    conn = sqlite3.connect(DB_NAME)\n",
    "    c = conn.cursor()\n",
    "    c.execute(\"\"\"CREATE TABLE IF NOT EXISTS daily_summaries\n",
    "                (date TEXT, avg_temp REAL, max_temp REAL, min_temp REAL, dominant_weather TEXT)\"\"\")\n",
    "    c.execute(\"INSERT INTO daily_summaries VALUES (?, ?, ?, ?, ?)\",\n",
    "                (daily_summary[\"date\"], daily_summary[\"avg_temp\"], daily_summary[\"max_temp\"],\n",
    "                 daily_summary[\"min_temp\"], daily_summary[\"dominant_weather\"]))\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "def check_alerting_thresholds(weather_data):\n",
    "    \"\"\"Check if weather data exceeds alerting thresholds\"\"\"\n",
    "    for data in weather_data:\n",
    "        if data[\"temp\"] > TEMP_THRESHOLD:\n",
    "            print(f\"Temperature exceeds threshold for {data['city']}: {data['temp']} °C\")\n",
    "\n",
    "def visualize_weather_data():\n",
    "    \"\"\"Visualize daily weather summaries\"\"\"\n",
    "    conn = sqlite3.connect(DB_NAME)\n",
    "    c = conn.cursor()\n",
    "    c.execute(\"SELECT * FROM daily_summaries\")\n",
    "    rows = c.fetchall()\n",
    "    dates = [row[0] for row in rows]\n",
    "    avg_temps = [row[1] for row in rows]\n",
    "    plt.plot(dates, avg_temps)\n",
    "    plt.xlabel(\"Date\")\n",
    "    plt.ylabel(\"Average Temperature (Celsius)\")\n",
    "    plt.title(\"Daily Weather Summaries\")\n",
    "    plt.xticks(rotation=45)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "def main():\n",
    "    print(\"Starting main function\")\n",
    "    weather_data = []\n",
    "    while True:\n",
    "        for city, city_id in CITY_IDS.items():\n",
    "            data = get_weather_data(city_id)\n",
    "            if data:\n",
    "                weather_data.append({\n",
    "                    \"city\": city,\n",
    "                    \"temp\": data[\"main\"][\"temp\"],  # Use the temperature in Celsius\n",
    "                    \"weather\": data[\"weather\"][0][\"main\"]  # Get the main weather condition\n",
    "                })\n",
    "\n",
    "        # Calculate daily summary and store it in the database\n",
    "        daily_summary = calculate_daily_summary(weather_data)\n",
    "        store_daily_summary(daily_summary)\n",
    "\n",
    "        # Check if any temperature exceeds the alerting threshold\n",
    "        check_alerting_thresholds(weather_data)\n",
    "\n",
    "        # Clear weather data for the next iteration\n",
    "        weather_data = []\n",
    "\n",
    "        # Sleep for a specified duration before the next API call\n",
    "        time.sleep(60 * 60)  # Sleep for 1 hour\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5ef469ed-7c02-426a-a17d-509c88017d73",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter the city London\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Weather in London:\n",
      "Main weather condition: Clouds\n",
      "Current temperature: 12.03°C\n",
      "Perceived temperature: 11.66°C\n",
      "Update time: 1729670005\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "def get_weather_data(city, api_key):\n",
    "  base_url = f\"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}\"\n",
    "  response = requests.get(base_url)\n",
    "  weather_data = response.json()\n",
    "\n",
    "  main_weather_condition = weather_data['weather'][0]['main']\n",
    "  current_temperature_kelvin = weather_data['main']['temp']\n",
    "  perceived_temperature_kelvin = weather_data['main']['feels_like']\n",
    "  update_time = weather_data['dt']\n",
    "\n",
    "  # Convert Kelvin to Celsius\n",
    "  current_temperature_celsius = current_temperature_kelvin - 273.15\n",
    "  perceived_temperature_celsius = perceived_temperature_kelvin - 273.15\n",
    "\n",
    "  print(f\"Weather in {city}:\")\n",
    "  print(f\"Main weather condition: {main_weather_condition}\")\n",
    "  print(f\"Current temperature: {current_temperature_celsius:.2f}°C\")  # Format to 2 decimal places\n",
    "  print(f\"Perceived temperature: {perceived_temperature_celsius:.2f}°C\")\n",
    "  print(f\"Update time: {update_time}\")\n",
    "\n",
    "city = input(\"Enter the city\")\n",
    "api_key =\"2e8a8c238b72f0695521a0507766af38\"\n",
    "get_weather_data(city, api_key)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fce24ee2-9c6b-4da0-a7a2-062147e943a8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "348d1e2f-76ee-4175-990d-9d38e61a626d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3068938-d4bf-414e-8f01-108c430812a8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
